import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { list } from "postcss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let homelink = "/";
  let listlink = "/list";
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center">
          <Link href={homelink}>홈</Link>
          <Link className="ml-10" href={listlink}>
            리스트
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
